const users = [
  { id: "1",
    name: "user 1",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "2",
    name: "user 2",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "3",
    name: "user 3",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "4",
    name: "user 4",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "5",
    name: "user 5",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "6",
    name: "user 6",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "7",
    name: "user 7",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "8",
    name: "user 8",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "9",
    name: "user 9",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "10",
    name: "user 10",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "11",
    name: "user 11",
    email: "user@gmailcom",
    rol: "usuario",
  },
  { id: "12",
    name: "user 12",
    email: "user@gmailcom",
    rol: "usuario",
  },
];

export default function handler(req, res) {
  res.status(200).json(users);
}
